### ISSUE TITLE
uncleaned join for the adpp data?

### ISSUE THREAD

**Issue by shajoezhu** [pharmaverse/pharmaverseadam#56] opened 2023-12-19 05:22 UTC
Several variables have .x and .y variables

```
> names(adpp)
 [1] "STUDYID"  "USUBJID"  "PPTESTCD" "PPTEST"   "PPCAT"    "PPORRES"  "PPORRESU" "PPSTRESU" "PPSPEC"   "PPRFDTC" 
[11] "TRTSDT.x" "TRTEDT.x" "DTHDT.x"  "EOSDT.x"  "TRT01P.x" "TRT01A.x" "ADT"      "ADY"      "PARAMCD"  "AVAL"    
[21] "AVALC"    "SRCDOM"   "SRCVAR"   "SRCSEQ"   "VISIT"    "VISITNUM" "AVISIT"   "AVISITN"  "TRTP"     "TRTA"    
[31] "AVALCA1N" "AVALCAT1" "SUBJID"   "RFSTDTC"  "RFENDTC"  "RFXSTDTC" "RFXENDTC" "RFICDTC"  "RFPENDTC" "DTHDTC"  
[41] "DTHFL"    "SITEID"   "AGE"      "AGEU"     "SEX"      "RACE"     "ETHNIC"   "ARMCD"    "ARM"      "ACTARMCD"
[51] "ACTARM"   "COUNTRY"  "DMDTC"    "DMDY"     "TRT01P.y" "TRT01A.y" "TRTSDTM"  "TRTSTMF"  "TRTEDTM"  "TRTETMF" 
[61] "TRTSDT.y" "TRTEDT.y" "TRTDURD"  "SCRFDT"   "EOSDT.y"  "EOSSTT"   "FRVDT"    "RANDDT"   "DTHDT.y"  "DTHADY"  
[71] "LDDTHELD" "LSTALVDT" "AGEGR1"   "SAFFL"    "RACEGR1"  "REGION1"  "LDDTHGR1" "DTH30FL"  "DTHA30FL" "DTHB30FL"
```

**Comment by manciniedoardo** [comment] 2024-01-03 09:03
This is a duplicate of #54 which has been resolved on the main admiral package by @jeffreyad (please correct me if i'm wrong) so this should be fixed in the next release.

**Closed by manciniedoardo** 2024-01-03 09:03 UTC
Labels: duplicate
